# GitHub workflow for generating SLSA3 provenance for QR-Code-Generator-Web-App

name: SLSA QR Code App Provenance Generator

on:
  workflow_dispatch:
  release:
    types: [created]  # Trigger when a GitHub release is created

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.hashes }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Flask QR Code App Artifact
        run: |
          mkdir -p dist
          zip -r dist/qr-code-generator.zip . -x "*.git*" "*.github*"

      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail
          echo "hashes=$(sha256sum dist/qr-code-generator.zip | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true
